import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="box-border bg-gradient-to-bl from-[#FFECEC] to-[#FFFFFF] h-[100vh] pt-[4rem]">
        <nav className="flex items-center justify-between text-[1.25rem] h-[3.75rem] px-[4rem] border-1">
          <div className="w-[22.5rem]">
            <ul className="flex justify-between">
              <li><a href="/">Home</a></li>
              <li><a href="#">Blogs</a></li>
              <li><a href="#">Projects</a></li>
              <li><a href="/resume.pdf" download>Resume</a></li>
            </ul>
          </div>
          <div className="w-[14.37rem]">
            <ul className="flex justify-between">
              <li><a href="https://github.com/Dimension5D" target="_blank">Github</a></li>
              <li><a href="https://www.linkedin.com/in/shubham-sharma3099/" target="_blank">LinkedIn</a></li>
              <li><a href="https://x.com/Dimension5D" target="_blank">X</a></li>
            </ul>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
